# Generated by Django 5.2.10 on 2026-01-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_populate_marseille_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="citydistrict",
            options={
                "ordering": ["city__name", "name"],
                "verbose_name": "City District",
                "verbose_name_plural": "City Districts",
            },
        ),
        migrations.AlterModelOptions(
            name="cityneighborhood",
            options={
                "ordering": ["district__city__name", "district__name", "name"],
                "verbose_name": "City Neighborhood",
                "verbose_name_plural": "City Neighborhoods",
            },
        ),
        migrations.AlterModelOptions(
            name="neighborhoodassociation",
            options={
                "ordering": [
                    "neighborhood__district__city__name",
                    "neighborhood__district__name",
                    "neighborhood__name",
                ],
                "verbose_name": "Neighborhood Association",
                "verbose_name_plural": "Neighborhood Associations",
            },
        ),
        migrations.AlterField(
            model_name="neighborhoodassociation",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Contact Email"),
        ),
        migrations.AlterField(
            model_name="neighborhoodassociation",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Contact Phone"),
        ),
        migrations.AlterField(
            model_name="neighborhoodassociation",
            name="neighborhood",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associations",
                to="core.cityneighborhood",
                verbose_name="City Neighborhood",
            ),
        ),
        migrations.AlterField(
            model_name="neighborhoodassociation",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
    ]
