# Generated by Django 6.0.2 on 2026-02-06 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_user_options_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("VERIFICATION", "Email Verification"),
                            ("PASSWORD_RESET", "Password Reset"),
                        ],
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        help_text="Stored temporarily, cleared on anonymization",
                        max_length=254,
                        verbose_name="Recipient Email",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Sent At")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("error_message", models.TextField(blank=True, verbose_name="Error Message")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Event",
                "verbose_name_plural": "Email Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="core_emaile_created_7f63c3_idx"),
                    models.Index(
                        fields=["user", "event_type"], name="core_emaile_user_id_546c18_idx"
                    ),
                ],
            },
        ),
    ]
