# Generated by Django 6.0.1 on 2026-02-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_email_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                blank=True, editable=False, null=True, unique=True, verbose_name="UUID"
            ),
        ),
    ]
