# Generated by Django 6.0.1 on 2026-02-07 09:52
import uuid

from django.db import migrations


def populate_user_uuids(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        user.uuid = uuid.uuid4()
        user.save(update_fields=["uuid"])


def reverse_populate_user_uuids(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.all().update(uuid=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_user_uuid_nullable"),
    ]

    operations = [
        migrations.RunPython(populate_user_uuids, reverse_populate_user_uuids),
    ]
