# Generated by Django 6.0.2 on 2026-03-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_make_user_uuid_non_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user account was soft-deleted. NULL if not deleted.",
                null=True,
                verbose_name="Deleted At",
            ),
        ),
    ]
