# Generated by Django 6.0.3 on 2026-06-01 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_add_soft_delete_to_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
