# Generated by Django 6.0.3 on 2026-10-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="newsletter_consent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user last agreed to receive the newsletter (GDPR proof of consent). Empty if they are not subscribed, or subscribed before this date was recorded.",
                null=True,
                verbose_name="Newsletter consent date",
            ),
        ),
    ]
