# Generated by Django 6.0.3 on 2026-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_user_newsletter_consent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_event_reminders",
            field=models.BooleanField(
                default=False,
                help_text="Email a reminder the day before events I am interested in.",
                verbose_name="Event reminders",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_poll_results",
            field=models.BooleanField(
                default=False,
                help_text="Email the results when a poll I voted in closes.",
                verbose_name="Poll results",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_project_updates",
            field=models.BooleanField(
                default=False,
                help_text="Email the news of projects I voted on or shared an idea about.",
                verbose_name="Project updates",
            ),
        ),
        migrations.AlterField(
            model_name="emailevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("VERIFICATION", "Email Verification"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("POLL_RESULTS", "Poll results"),
                    ("PROJECT_UPDATE", "Project update"),
                    ("EVENT_REMINDER", "Event reminder"),
                ],
                max_length=20,
                verbose_name="Event Type",
            ),
        ),
        migrations.CreateModel(
            name="NotificationDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=30, verbose_name="Kind")),
                (
                    "key",
                    models.CharField(
                        help_text="What was notified, e.g. project:12",
                        max_length=100,
                        verbose_name="Key",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Sent At")),
            ],
            options={
                "verbose_name": "Notification sent",
                "verbose_name_plural": "Notifications sent",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "key"), name="unique_notification_dispatch"
                    )
                ],
            },
        ),
    ]
