# Generated by Django 6.0.3 on 2026-10-07 13:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Display the band at the top of every page of the website.",
                        verbose_name="Show the announcement",
                    ),
                ),
                (
                    "message",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Keep it short: one or two sentences. Visitors who closed it see it again once you change it.",
                        verbose_name="Message",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("important", "Important"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Style",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
            },
        ),
    ]
