# Generated by Django 6.0.3 on 2026-10-08 09:10

import django.db.models.deletion
import publications.geo
from django.conf import settings
from django.db import migrations, models


def name_existing_associations(apps, schema_editor):
    """Existing associations were named after their neighborhood."""
    NeighborhoodAssociation = apps.get_model("core", "NeighborhoodAssociation")
    for association in NeighborhoodAssociation.objects.select_related("neighborhood__district"):
        neighborhood = association.neighborhood
        association.name = (
            f"{neighborhood.name}, {neighborhood.district.name}"
            if neighborhood
            else f"Association {association.pk}"
        )[:150]
        association.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_announcement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="neighborhoodassociation",
            options={
                "ordering": ["name"],
                "verbose_name": "Neighborhood Association",
                "verbose_name_plural": "Neighborhood Associations",
            },
        ),
        migrations.AddField(
            model_name="neighborhoodassociation",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="neighborhoodassociation",
            name="address_location",
            field=models.JSONField(
                blank=True, editable=False, null=True, verbose_name="Address location"
            ),
        ),
        migrations.AddField(
            model_name="neighborhoodassociation",
            name="area",
            field=models.JSONField(
                blank=True,
                help_text="Residents whose address lies in this area are attached to the association.",
                null=True,
                validators=[publications.geo.validate_area],
                verbose_name="Area",
            ),
        ),
        migrations.AddField(
            model_name="neighborhoodassociation",
            name="name",
            field=models.CharField(default="", max_length=150, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="neighborhoodassociation",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["ASSOCIATION_MEMBER", "ADMIN"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_for_associations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="user",
            name="association",
            field=models.ForeignKey(
                blank=True,
                help_text="The association whose area contains the user's address.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="core.neighborhoodassociation",
                verbose_name="Neighborhood Association",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="neighborhoodassociation",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="neighborhoodassociation",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="associations",
                to="core.cityneighborhood",
                verbose_name="City Neighborhood",
            ),
        ),
        migrations.RunPython(name_existing_associations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="neighborhoodassociation",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Name"),
        ),
    ]
