# Generated by Django 6.0.3 on 2026-10-08 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_address_geocoding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="neighborhoodassociation",
            name="neighborhood",
        ),
    ]
