# Generated by Django 6.0.3 on 2026-10-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_association_neighborhood"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="Task")),
                (
                    "arguments",
                    models.CharField(blank=True, max_length=255, verbose_name="Arguments"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Running"),
                            ("SUCCESS", "Succeeded"),
                            ("FAILURE", "Failed"),
                            ("RETRY", "Retrying"),
                        ],
                        default="STARTED",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("worker", models.CharField(blank=True, max_length=255, verbose_name="Worker")),
                ("started_at", models.DateTimeField(db_index=True, verbose_name="Started")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Finished"),
                ),
                ("result", models.CharField(blank=True, max_length=255, verbose_name="Result")),
                ("error", models.TextField(blank=True, verbose_name="Error")),
            ],
            options={
                "verbose_name": "Task run",
                "verbose_name_plural": "Task runs",
                "ordering": ["-started_at"],
            },
        ),
    ]
