# Generated by Django 6.0.3 on 2026-10-08 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def map_roles(apps, schema_editor):
    """Association members become moderators if they were in the Moderators group,
    editors otherwise; then every staff account joins the group of its role."""
    User = apps.get_model("core", "User")
    Group = apps.get_model("auth", "Group")
    groups = {g.name: g for g in Group.objects.filter(name__in=["Editors", "Moderators"])}

    for user in User.objects.filter(role="ASSOCIATION_MEMBER"):
        moderator = user.groups.filter(name="Moderators").exists()
        user.role = "MODERATOR" if moderator else "EDITOR"
        user.save(update_fields=["role"])

    wanted = {"EDITOR": "Editors", "MODERATOR": "Moderators", "ADMIN": "Moderators"}
    for user in User.objects.filter(role__in=list(wanted), is_active=True):
        for name, group in groups.items():
            if name == wanted[user.role]:
                user.groups.add(group)
            else:
                user.groups.remove(group)


def unmap_roles(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(role__in=["EDITOR", "MODERATOR"]).update(role="ASSOCIATION_MEMBER")


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0002_initial_data"),
        ("core", "0016_task_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "participation_requires_subscription",
                    models.BooleanField(
                        default=False,
                        help_text="Only subscribers may vote and share ideas. Turn on once subscribing is possible: other users will be invited to subscribe.",
                        verbose_name="Reserve participation to subscribers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Features",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_participation_stats", "Can see vote and idea statistics"),
                    ("manage_tasks", "Can see and start background tasks"),
                ],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_subscriber",
            field=models.BooleanField(
                default=False,
                help_text="Subscribers may vote and share ideas when participation is reserved to them (Settings › Features).",
                verbose_name="Subscriber",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Subscribed on"),
        ),
        migrations.AlterField(
            model_name="neighborhoodassociation",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["EDITOR", "MODERATOR", "ADMIN"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_for_associations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CITIZEN", "Citizen"),
                    ("EDITOR", "Editor"),
                    ("MODERATOR", "Moderator"),
                    ("ADMIN", "Administrator"),
                ],
                default="CITIZEN",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.RunPython(map_roles, unmap_roles),
    ]
