# Generated by Django 6.0.3 on 2026-10-08 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_roles_and_features"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_participation_stats", "Can see vote and idea statistics"),
                    ("manage_tasks", "Can see and start background tasks"),
                    ("view_audit_log", "Can see the activity log"),
                ],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="taskrun",
            name="launched_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Started by",
            ),
        ),
        migrations.AlterField(
            model_name="taskrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("STARTED", "Running"),
                    ("SUCCESS", "Succeeded"),
                    ("FAILURE", "Failed"),
                    ("RETRY", "Retrying"),
                ],
                default="STARTED",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
