# Generated by Django 6.0.3 on 2026-10-08 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def copy_subscribers(apps, schema_editor):
    """Users marked as subscribers get a membership from their subscription date."""
    from django.utils import timezone

    User = apps.get_model("core", "User")
    Membership = apps.get_model("core", "Membership")
    for user in User.objects.filter(is_subscriber=True):
        since = user.subscribed_at or timezone.now()
        Membership.objects.create(
            user=user, starts_on=timezone.localdate(since), note="Reprise de l'ancien statut"
        )


def restore_subscribers(apps, schema_editor):
    from django.utils import timezone

    User = apps.get_model("core", "User")
    Membership = apps.get_model("core", "Membership")
    today = timezone.localdate()
    for membership in Membership.objects.filter(starts_on__lte=today).exclude(ends_on__lt=today):
        User.objects.filter(pk=membership.user_id).update(
            is_subscriber=True, subscribed_at=timezone.now()
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_audit_trail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "starts_on",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="Start"),
                ),
                (
                    "ends_on",
                    models.DateField(
                        blank=True,
                        help_text="Leave empty for a membership with no end.",
                        null=True,
                        verbose_name="End",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="E.g. how the membership was paid.",
                        max_length=255,
                        verbose_name="Note",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Recorded on")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recorded by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "ordering": ["-starts_on", "-pk"],
            },
        ),
        migrations.RunPython(copy_subscribers, restore_subscribers),
        migrations.RemoveField(model_name="user", name="is_subscriber"),
        migrations.RemoveField(model_name="user", name="subscribed_at"),
        migrations.RenameField(
            model_name="featureflags",
            old_name="participation_requires_subscription",
            new_name="participation_requires_membership",
        ),
        migrations.AlterField(
            model_name="featureflags",
            name="participation_requires_membership",
            field=models.BooleanField(
                default=False,
                help_text="Only members may vote and share ideas. Turn on once joining is possible: other users will be invited to become members.",
                verbose_name="Reserve participation to members",
            ),
        ),
    ]
