# Generated by Django 6.0.3 on 2026-10-08 15:58

import publications.geo
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text='Shown alone, e.g. "7e arrondissement de Marseille".',
                        max_length=150,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_in",
                    models.CharField(
                        blank=True,
                        help_text='Completes "Projects located…", e.g. "dans le 7e arrondissement de Marseille".',
                        max_length=160,
                        verbose_name="Name in a sentence",
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        blank=True,
                        help_text="Addresses are searched in this city, e.g. Marseille.",
                        max_length=100,
                        verbose_name="City",
                    ),
                ),
                (
                    "city_code",
                    models.CharField(
                        blank=True,
                        help_text="Official code of the commune (not the postal code), e.g. 13055 for Marseille. Empty: addresses are searched in the whole of France.",
                        max_length=5,
                        verbose_name="City INSEE code",
                    ),
                ),
                (
                    "postal_codes",
                    models.CharField(
                        blank=True,
                        help_text="Separated by commas. The participation statistics count residents with these postal codes by default. Empty: everyone is counted.",
                        max_length=200,
                        verbose_name="Local postal codes",
                    ),
                ),
                (
                    "boundary",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[publications.geo.validate_area],
                        verbose_name="Boundary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Territory",
            },
        ),
    ]
