# Generated by Django 6.0.3 on 2026-10-08 16:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_territory_marseille_7e"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        blank=True,
                        help_text="In the header, the page titles and the emails.",
                        max_length=60,
                        verbose_name="Website name",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Under the name, at the bottom of every page.",
                        max_length=120,
                        verbose_name="Tagline",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Shown to visitors who want to write to you.",
                        max_length=254,
                        verbose_name="Contact email",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        help_text="Buttons, links and highlights, as #rrggbb. Choose a colour dark enough to read on a white background. Empty: the default orange.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "A colour like #e94f37."
                            )
                        ],
                        verbose_name="Main colour",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        blank=True,
                        help_text="Dark sections and some badges, as #rrggbb. Empty: the default navy.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "A colour like #e94f37."
                            )
                        ],
                        verbose_name="Secondary colour",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="A square image works best: it is also the browser tab icon.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "signup_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Beside the sign-up form, on large screens. A photo of the area.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Sign-up photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branding",
            },
        ),
    ]
