# Generated by Django 6.0.3 on 2026-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_territory_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("VERIFICATION", "Email Verification"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("INVITATION", "Invitation"),
                    ("POLL_RESULTS", "Poll results"),
                    ("PROJECT_UPDATE", "Project update"),
                    ("EVENT_REMINDER", "Event reminder"),
                ],
                max_length=20,
                verbose_name="Event Type",
            ),
        ),
    ]
