# Generated by Django 6.0.3 on 2026-10-08 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_invitation_email_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citydistrict",
            name="city",
        ),
        migrations.RemoveField(
            model_name="cityneighborhood",
            name="district",
        ),
        migrations.RemoveField(
            model_name="user",
            name="neighborhood",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="CityDistrict",
        ),
        migrations.DeleteModel(
            name="CityNeighborhood",
        ),
    ]
