# Generated by Django 6.0.3 on 2026-10-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_remove_legacy_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="branding",
            name="initial_values",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
