# Generated by Django 6.0.3 on 2026-10-08 21:24

import core.models.branding
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_branding_initial_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="branding",
            name="background_color",
            field=models.CharField(
                blank=True,
                help_text="Behind the text, as #rrggbb. Empty: the default off-white.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "A colour like #e94f37."
                    )
                ],
                verbose_name="Background colour",
            ),
        ),
        migrations.AddField(
            model_name="branding",
            name="font_body",
            field=models.CharField(
                blank=True,
                max_length=40,
                validators=[core.models.branding.validate_body_font],
                verbose_name="Text font",
            ),
        ),
        migrations.AddField(
            model_name="branding",
            name="font_display",
            field=models.CharField(
                blank=True,
                help_text="Large titles and headings.",
                max_length=40,
                validators=[core.models.branding.validate_display_font],
                verbose_name="Title font",
            ),
        ),
        migrations.AddField(
            model_name="branding",
            name="text_color",
            field=models.CharField(
                blank=True,
                help_text="As #rrggbb. It must read well on the background (contrast of 4.5:1 at least). Empty: the default near-black.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "A colour like #e94f37."
                    )
                ],
                verbose_name="Text colour",
            ),
        ),
    ]
