# Generated by Django 5.2.10 on 2026-01-17 13:33

from django.db import migrations

_LEGAL_INDEX_SLUG = "legal"


def _create_legal_index(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")
    LegalIndexPage = apps.get_model("legal", "LegalIndexPage")
    HomePage = apps.get_model("home", "HomePage")
    Page = apps.get_model("wagtailcore", "Page")

    if LegalIndexPage.objects.filter(slug=_LEGAL_INDEX_SLUG).exists():
        return

    legal_index_page_content_type, __ = ContentType.objects.get_or_create(
        model="legalindexpage", app_label="legal"
    )

    home_page = HomePage.objects.first()
    if not home_page:
        raise ValueError("No HomePage found. Cannot create LegalIndexPage.")

    # Get the last child of the homepage to determine the next path
    children = Page.objects.filter(
        path__startswith=home_page.path, depth=home_page.depth + 1
    ).order_by("path")
    last_child = children.last()

    if last_child:
        # If children exist, increment the last child's path
        path_len = len(last_child.path)
        last_path_int = int(last_child.path[path_len - 4 :])
        new_suffix = f"{last_path_int + 1:04d}"
        new_path = last_child.path[:-4] + new_suffix
    else:
        # If no children, append '0001' to parent path
        new_path = home_page.path + "0001"

    LegalIndexPage.objects.create(
        title="Légal",
        draft_title="Légal",
        slug=_LEGAL_INDEX_SLUG,
        content_type=legal_index_page_content_type,
        path=new_path,
        depth=home_page.depth + 1,
        numchild=0,
        url_path=home_page.url_path + _LEGAL_INDEX_SLUG + "/",
        locale_id=home_page.locale_id,
        live=True,
        show_in_menus=True,
    )

    home_page.numchild += 1
    home_page.save(update_fields=["numchild"])


def _remove_legal_index(apps, schema_editor):
    LegalIndexPage = apps.get_model("legal", "LegalIndexPage")
    HomePage = apps.get_model("home", "HomePage")

    page = LegalIndexPage.objects.filter(slug=_LEGAL_INDEX_SLUG).first()
    if page:
        # Note: Finding parent via path prefix is safer in migrations
        parent_path = page.path[:-4]
        parent = HomePage.objects.filter(path=parent_path).first()
        if parent:
            parent.numchild = max(0, parent.numchild - 1)
            parent.save(update_fields=["numchild"])
        page.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0001_initial"),
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0040_page_draft_title"),
    ]

    operations = [
        migrations.RunPython(_create_legal_index, _remove_legal_index),
    ]
