# Generated by Django 5.2.10 on 2026-01-17 16:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0002_create_legal_index"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeOfConductPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("text", 0), ("image", 1), ("image_text", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "document-link",
                                        "ul",
                                        "ol",
                                        "blockquote",
                                        "superscript",
                                        "subscript",
                                    ],
                                    "label": "Text",
                                    "template": "core/blocks/rich_text_block.html",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {
                                    "label": "Image",
                                    "template": "core/blocks/image_block.html",
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("left", "Left"), ("right", "Right")],
                                    "label": "Image Position",
                                },
                            ),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Text", "required": True},
                            ),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image", "required": True},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Alt Text",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("position", 2),
                                        ("paragraph", 3),
                                        ("image", 4),
                                        ("alt_text", 5),
                                    ]
                                ],
                                {
                                    "label": "Image & Text Row",
                                    "template": "core/blocks/image_text_block.html",
                                },
                            ),
                        },
                        help_text="This content should not change often as the user is prompted to accept it whenever it changes.",
                        verbose_name="Code of conduct body content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code of Conduct Page",
                "verbose_name_plural": "Code of Conduct Pages",
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
