# Generated by Django 5.2.10 on 2026-01-17 13:33

from django.db import migrations

_CODE_OF_CONDUCT_SLUG = "charte-de-conduite"
_LEGAL_INDEX_SLUG = "legal"


def _create_code_of_conduct(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")
    CodeOfConductPage = apps.get_model("legal", "CodeOfConductPage")
    LegalIndexPage = apps.get_model("legal", "LegalIndexPage")
    Page = apps.get_model("wagtailcore", "Page")

    if CodeOfConductPage.objects.filter(slug=_CODE_OF_CONDUCT_SLUG).exists():
        return

    code_of_conduct_page_content_type, __ = ContentType.objects.get_or_create(
        model="codeofconductpage", app_label="legal"
    )

    legal_index_page = LegalIndexPage.objects.filter(slug=_LEGAL_INDEX_SLUG).first()
    if not legal_index_page:
        # Try to find any legal index page
        legal_index_page = LegalIndexPage.objects.first()
        if not legal_index_page:
            print("LegalIndexPage not found. Cannot create CodeOfConductPage.")
            return

    # Get the last child of the legal index page to determine the next path
    children = Page.objects.filter(
        path__startswith=legal_index_page.path, depth=legal_index_page.depth + 1
    ).order_by("path")
    last_child = children.last()

    if last_child:
        # If children exist, increment the last child's path
        path_len = len(last_child.path)
        last_path_int = int(last_child.path[path_len - 4 :])
        new_suffix = f"{last_path_int + 1:04d}"
        new_path = last_child.path[:-4] + new_suffix
    else:
        # If no children, append '0001' to parent path
        new_path = legal_index_page.path + "0001"

    CodeOfConductPage.objects.create(
        title="Charte de bonne conduite",
        draft_title="Charte de bonne conduite",
        slug=_CODE_OF_CONDUCT_SLUG,
        content_type=code_of_conduct_page_content_type,
        path=new_path,
        depth=legal_index_page.depth + 1,
        numchild=0,
        url_path=legal_index_page.url_path + _CODE_OF_CONDUCT_SLUG + "/",
        locale_id=legal_index_page.locale_id,
        live=True,
        show_in_menus=True,
    )

    legal_index_page.numchild += 1
    legal_index_page.save(update_fields=["numchild"])


def _remove_code_of_conduct(apps, schema_editor):
    CodeOfConductPage = apps.get_model("legal", "CodeOfConductPage")
    LegalIndexPage = apps.get_model("legal", "LegalIndexPage")

    page = CodeOfConductPage.objects.filter(slug=_CODE_OF_CONDUCT_SLUG).first()
    if page:
        # Note: Finding parent via path prefix is safer in migrations
        parent_path = page.path[:-4]
        parent = LegalIndexPage.objects.filter(path=parent_path).first()
        if parent:
            parent.numchild = max(0, parent.numchild - 1)
            parent.save(update_fields=["numchild"])
        page.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0003_codeofconductpage"),
    ]

    operations = [
        migrations.RunPython(_create_code_of_conduct, _remove_code_of_conduct),
    ]
