# Generated by Django 5.2.10 on 2026-01-17 16:39

from django.db import migrations

_LEGAL_INDEX_SLUG = "legal"

_LEGAL_PAGES = [
    {
        "model_name": "TermsOfServicePage",
        "title": "Termes d'utilisation",
        "slug": "termes",
        "lower_model_name": "termsofservicepage",
    },
    {
        "model_name": "PrivacyPolicyPage",
        "title": "Politique de confidentialité",
        "slug": "confidentialite",
        "lower_model_name": "privacypolicypage",
    },
    {
        "model_name": "CookiesPolicyPage",
        "title": "Politique de cookies",
        "slug": "cookies",
        "lower_model_name": "cookiespolicypage",
    },
]


def _create_pages(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")
    LegalIndexPage = apps.get_model("legal", "LegalIndexPage")
    Page = apps.get_model("wagtailcore", "Page")

    legal_index_page = LegalIndexPage.objects.filter(slug=_LEGAL_INDEX_SLUG).first()
    if not legal_index_page:
        legal_index_page = LegalIndexPage.objects.first()
        if not legal_index_page:
            print("LegalIndexPage not found. Skipping creation of legal child pages.")
            return

    for page_def in _LEGAL_PAGES:
        model_name = page_def["model_name"]
        slug = page_def["slug"]
        title = page_def["title"]
        lower_model_name = page_def["lower_model_name"]

        ModelClass = apps.get_model("legal", model_name)

        if ModelClass.objects.filter(slug=slug).exists():
            continue

        content_type, __ = ContentType.objects.get_or_create(
            model=lower_model_name, app_label="legal"
        )

        # Always re-query children to get latest path
        children = Page.objects.filter(
            path__startswith=legal_index_page.path, depth=legal_index_page.depth + 1
        ).order_by("path")
        last_child = children.last()

        if last_child:
            path_len = len(last_child.path)
            last_path_int = int(last_child.path[path_len - 4 :])
            new_suffix = f"{last_path_int + 1:04d}"
            new_path = last_child.path[:-4] + new_suffix
        else:
            new_path = legal_index_page.path + "0001"

        ModelClass.objects.create(
            title=title,
            draft_title=title,
            slug=slug,
            content_type=content_type,
            path=new_path,
            depth=legal_index_page.depth + 1,
            numchild=0,
            url_path=legal_index_page.url_path + slug + "/",
            locale_id=legal_index_page.locale_id,
            live=True,
            show_in_menus=True,
        )

        legal_index_page.numchild += 1
        legal_index_page.save(update_fields=["numchild"])


def _remove_pages(apps, schema_editor):
    LegalIndexPage = apps.get_model("legal", "LegalIndexPage")

    for page_def in _LEGAL_PAGES:
        model_name = page_def["model_name"]
        slug = page_def["slug"]
        ModelClass = apps.get_model("legal", model_name)

        page = ModelClass.objects.filter(slug=slug).first()
        if page:
            parent_path = page.path[:-4]
            parent = LegalIndexPage.objects.filter(path=parent_path).first()
            if parent:
                parent.numchild = max(0, parent.numchild - 1)
                parent.save(update_fields=["numchild"])
            page.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0005_cookiespolicypage_privacypolicypage_and_more"),
    ]

    operations = [
        migrations.RunPython(_create_pages, _remove_pages),
    ]
