# Generated by Django 5.2.10 on 2026-01-17 17:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0006_create_legal_pages_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeofconductpage",
            name="content",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="This content should not change often as the user is prompted to accept it whenever it changes.",
                verbose_name="Code of conduct body content",
            ),
        ),
        migrations.AlterField(
            model_name="cookiespolicypage",
            name="content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Cookies policy body content"
            ),
        ),
        migrations.AlterField(
            model_name="privacypolicypage",
            name="content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Privacy policy body content"
            ),
        ),
        migrations.AlterField(
            model_name="termsofservicepage",
            name="content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Terms of service body content"
            ),
        ),
    ]
