# Generated by Django 5.2.10 on 2026-01-17 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0007_alter_codeofconductpage_content_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeOfConductConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consented_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Consented at"),
                ),
                (
                    "consent_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Consent IP Address"
                    ),
                ),
                (
                    "policy_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="code_of_conduct_consents",
                        to="wagtailcore.revision",
                        verbose_name="Policy Version",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_of_conduct_consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code of Conduct Consent",
                "verbose_name_plural": "Code of Conduct Consents",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "policy_revision"),
                        name="unique_consent_per_version",
                    )
                ],
            },
        ),
    ]
