# Generated by Django 5.2.10 on 2026-01-14 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0002_create_pedagogy_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedagogyindexpage",
            options={
                "verbose_name": "Pedagogy Entries Index",
                "verbose_name_plural": "Pedagogy Entries Index",
            },
        ),
    ]
