# Generated by Django 5.2.10 on 2026-01-15 10:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0003_alter_pedagogyindexpage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedagogyindexpage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Content for the pedagogy entries page.",
                verbose_name="Page body content",
            ),
        ),
        migrations.AlterField(
            model_name="pedagogyindexpage",
            name="page_introduction",
            field=models.TextField(
                blank=True,
                default="Voici un ensemble d'outils et de ressources pédagogiques pour vous aider à vous investir dans la vie de votre quartier.",
                help_text="Small introduction shown above the pedagogy card list.",
                verbose_name="Page introduction",
            ),
        ),
    ]
