# Generated by Django 5.2.10 on 2026-01-15 16:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0004_alter_pedagogyindexpage_body_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedagogycardpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="A brief description of the pedagogy card.",
                verbose_name="Card description",
            ),
        ),
        migrations.AddField(
            model_name="pedagogycardpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Card image",
            ),
        ),
    ]
