# Generated by Django 5.2.10 on 2026-01-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0005_pedagogycardpage_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedagogycardpage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the pedagogy card.",
                verbose_name="Card description",
            ),
        ),
    ]
