# Generated by Django 5.2.10 on 2026-01-16 08:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0008_pedagogyresource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedagogycardpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 1), ("image_text", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "Text",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"label": "Image", "template": "core/blocks/image_block.html"},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image Position",
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Text", "required": True},
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Alt Text", "max_length": 255, "required": True},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("position", 2),
                                ("paragraph", 3),
                                ("image", 4),
                                ("alt_text", 5),
                            ]
                        ],
                        {
                            "label": "Image & Text Row",
                            "template": "core/blocks/image_text_block.html",
                        },
                    ),
                },
                help_text="The main content of the pedagogy card.",
                verbose_name="Card body content",
            ),
        ),
    ]
