# Generated by Django 6.0.2 on 2026-02-26 17:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0010_alter_pedagogycardpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedagogycardpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("text_centered", 1), ("image", 2), ("image_text", 7), ("faq", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "Text",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "label": "DEPRECATED Centered Text",
                            "template": "core/blocks/centered_text_block.html",
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"label": "Image", "template": "core/blocks/image_block.html"},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image Position",
                        },
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": True}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Image Alt Text (For accessibility, SEO, and in case the image fails to load)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("position", 3), ("paragraph", 4), ("image", 5), ("alt_text", 6)]],
                        {
                            "label": "DEPRECATED Image & Text Row",
                            "template": "core/blocks/image_text_block.html",
                        },
                    ),
                    8: ("core.blocks.FAQBlock", (), {"label": "FAQ Block"}),
                },
                help_text="The main content of the pedagogy card.",
                verbose_name="Card body content",
            ),
        ),
    ]
