# Generated by Django 6.0.2 on 2026-03-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0011_alter_pedagogycardpage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedagogycardpage",
            name="show_toc",
            field=models.BooleanField(
                default=True,
                help_text="Display the table of contents in the sidebar",
                verbose_name="Show table of contents",
            ),
        ),
    ]
