# Generated by Django 6.0.2 on 2026-02-26 18:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0011_alter_pedagogycardpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedagogycardpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 3),
                    ("text_centered", 4),
                    ("image", 5),
                    ("image_text", 10),
                    ("faq", 11),
                    ("two_column", 14),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "DEPRECATED Text",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Justification",
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "Content",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("justification", 1), ("text", 2)]], {}),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "label": "DEPRECATED Centered Text",
                            "template": "core/blocks/centered_text_block.html",
                        },
                    ),
                    5: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"label": "Image", "template": "core/blocks/image_block.html"},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image Position",
                        },
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": True}),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Image Alt Text (For accessibility, SEO, and in case the image fails to load)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("position", 6), ("paragraph", 7), ("image", 8), ("alt_text", 9)]],
                        {},
                    ),
                    11: ("core.blocks.FAQBlock", (), {}),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 0),
                                ("rich_text", 3),
                                ("text_centered", 4),
                                ("image", 5),
                                ("image_text", 10),
                                ("faq", 11),
                            ]
                        ],
                        {"label": "Left Column Content"},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 0),
                                ("rich_text", 3),
                                ("text_centered", 4),
                                ("image", 5),
                                ("image_text", 10),
                                ("faq", 11),
                            ]
                        ],
                        {"label": "Right Column Content"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 12), ("right_column", 13)]],
                        {},
                    ),
                },
                help_text="The main content of the pedagogy card.",
                verbose_name="Card body content",
            ),
        ),
    ]
