# Generated by Django 6.0.3 on 2026-10-07 18:27

import json

import pedagogy.models.pedagogy_index
import wagtail.fields
from django.db import migrations


def rich_text(html):
    return {
        "type": "rich_text",
        "value": {"justification": "left", "text": html, "max_width": None},
    }


def move_body_into_content(apps, schema_editor):
    """The page becomes its default blocks, then its former body text, if any.

    The latest revision is updated too: the editor opens it, not the page row.
    """
    Page = apps.get_model("pedagogy", "PedagogyIndexPage")
    for page in Page.objects.all():
        content = [{"type": "card_list", "value": {"label": "", "title": ""}}]
        if page.body:
            content.append(rich_text(page.body))
        page.content = json.dumps(content)
        page.save(update_fields=["content"])
        if page.latest_revision_id:
            revision = page.latest_revision
            body = revision.content.pop("body", "")
            revision_content = [{"type": "card_list", "value": {"label": "", "title": ""}}]
            if body:
                revision_content.append(rich_text(body))
            revision.content["content"] = json.dumps(revision_content)
            revision.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0013_alter_pedagogycardpage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedagogyindexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("card_list", 2),
                    ("section", 22),
                    ("join", 27),
                    ("open_projects", 29),
                    ("upcoming_events", 31),
                    ("recent_publications", 33),
                    ("rich_text", 37),
                    ("image", 38),
                    ("cards", 39),
                    ("faq", 40),
                    ("vertical_spacer", 43),
                    ("call_to_action_button", 44),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Small label", "max_length": 40, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 120, "required": False},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("label", 0), ("title", 1)]], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Shown above the title, e.g. “Who we are”.",
                            "label": "Small label",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Introduction", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("plain", "Plain"), ("sand", "Sand"), ("navy", "Navy")],
                            "label": "Background",
                        },
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Title above the content"),
                                ("split", "Title on the left, content on the right"),
                            ],
                            "label": "Layout",
                        },
                    ),
                    7: ("home.blocks.SectionTextBlock", (), {}),
                    8: ("home.blocks.StepsBlock", (), {}),
                    9: ("home.blocks.KeyFiguresBlock", (), {}),
                    10: ("home.blocks.QuotesBlock", (), {}),
                    11: ("home.blocks.SectionFAQBlock", (), {}),
                    12: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (1/3 Width)"),
                                ("medium", "Medium (1/2 Width)"),
                                ("large", "Large (2/3 Width)"),
                                ("full", "Full Width"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the image's default alt text",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 12), ("size", 13), ("alt_text", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button Text", "required": True},
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary"), ("secondary", "Secondary")],
                            "label": "Button Type",
                        },
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "label": "Button Alignment",
                        },
                    ),
                    19: ("wagtail.blocks.URLBlock", (), {"label": "Button Link", "required": True}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 16), ("style", 17), ("alignment", 18), ("url", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 7),
                                ("steps", 8),
                                ("key_figures", 9),
                                ("quotes", 10),
                                ("faq", 11),
                                ("image", 15),
                                ("button", 20),
                            ]
                        ],
                        {"label": "Content", "required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 3),
                                ("title", 1),
                                ("introduction", 4),
                                ("tone", 5),
                                ("layout", 6),
                                ("content", 21),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "Title", "max_length": 120}),
                    24: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": False}),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leads to the registration form.",
                            "label": "Button for visitors",
                            "max_length": 40,
                        },
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leads to their email notification settings.",
                            "label": "Button for signed-in members",
                            "max_length": 40,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 23), ("text", 24), ("button", 25), ("member_button", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Maximum number of projects",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("title", 23), ("limit", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Maximum number of events",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("title", 23), ("limit", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "label": "Number of Publications",
                            "max_value": 20,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("number_of_publications", 32)]],
                        {"group": "Live content"},
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Justification",
                        },
                    ),
                    35: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "Content",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    36: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "label": "Max Width (in pixels, optional)",
                            "min_value": 0,
                            "placeholder": "Leave blank for full width",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("justification", 34), ("text", 35), ("max_width", 36)]],
                        {"group": "Other blocks"},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 12), ("size", 13), ("alt_text", 14)]],
                        {"group": "Other blocks"},
                    ),
                    39: ("core.blocks.CardListBlock", (), {"group": "Other blocks"}),
                    40: ("core.blocks.FAQBlock", (), {"group": "Other blocks"}),
                    41: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 20,
                            "label": "Height (in pixels)",
                            "min_value": 0,
                            "required": True,
                        },
                    ),
                    42: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Hide on Mobile", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("height", 41), ("hide_on_mobile", 42)]],
                        {"group": "Other blocks"},
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 16), ("style", 17), ("alignment", 18), ("url", 19)]],
                        {"group": "Other blocks"},
                    ),
                },
                default=pedagogy.models.pedagogy_index.default_content,
                help_text="The list of cards and the parts around it.",
                verbose_name="Page content",
            ),
        ),
        migrations.RunPython(move_body_into_content, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="pedagogyindexpage",
            name="body",
        ),
    ]
