# Generated by Django 5.2.10 on 2026-01-14 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={
                "verbose_name": "Page d'accueil",
                "verbose_name_plural": "Pages d'accueil",
            },
        ),
    ]
