# Generated by Django 6.0.1 on 2026-01-30 16:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_homepage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("text_centered", 1),
                    ("image", 2),
                    ("image_text", 7),
                    ("hero", 14),
                    ("cards", 15),
                    ("testimonial", 18),
                    ("recent_publications", 20),
                    ("faq", 21),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "Text",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "label": "Centered Text",
                            "template": "core/blocks/centered_text_block.html",
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"label": "Image", "template": "core/blocks/image_block.html"},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image Position",
                        },
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": True}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Alt Text", "max_length": 255, "required": True},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("position", 3), ("paragraph", 4), ("image", 5), ("alt_text", 6)]],
                        {
                            "label": "Image & Text Row",
                            "template": "core/blocks/image_text_block.html",
                        },
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    9: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    10: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    11: ("wagtail.blocks.CharBlock", (), {"max_length": 255, "required": True}),
                    12: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    13: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 8),
                                ("subtitle", 9),
                                ("image", 10),
                                ("alt_text", 11),
                                ("cta_link", 12),
                                ("cta_text", 13),
                            ]
                        ],
                        {"label": "Hero Block"},
                    ),
                    15: ("core.blocks.CardListBlock", (), {"label": "Card List Block"}),
                    16: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    17: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 16),
                                ("author_name", 8),
                                ("author_title", 13),
                                ("author_image", 17),
                            ]
                        ],
                        {"label": "Testimonial Block"},
                    ),
                    19: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "label": "Number of Publications",
                            "max_value": 20,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("number_of_publications", 19)]],
                        {"label": "Recent Publications Block"},
                    ),
                    21: ("core.blocks.FAQBlock", (), {"label": "FAQ Block"}),
                },
                help_text="The main content of the home page.",
                verbose_name="Home page content",
            ),
        ),
    ]
