# Generated by Django 6.0.1 on 2026-02-03 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_homepage_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
    ]
