# Generated by Django 6.0.2 on 2026-02-26 17:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_homepage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("text_centered", 1),
                    ("image", 2),
                    ("image_text", 7),
                    ("faq", 8),
                    ("hero", 14),
                    ("testimonial", 19),
                    ("recent_publications", 21),
                    ("cards", 22),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "Text",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "label": "DEPRECATED Centered Text",
                            "template": "core/blocks/centered_text_block.html",
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"label": "Image", "template": "core/blocks/image_block.html"},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image Position",
                        },
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": True}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Image Alt Text (For accessibility, SEO, and in case the image fails to load)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("position", 3), ("paragraph", 4), ("image", 5), ("alt_text", 6)]],
                        {
                            "label": "DEPRECATED Image & Text Row",
                            "template": "core/blocks/image_text_block.html",
                        },
                    ),
                    8: ("core.blocks.FAQBlock", (), {"label": "FAQ Block"}),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Title", "required": True}),
                    10: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Subtitle (Optional)", "required": False},
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Background Image"},
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "label": "Call-to-Action Link (Leave blank if no CTA button)",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Call-to-Action Text (Leave blank if no CTA button)",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 9),
                                ("subtitle", 10),
                                ("image", 11),
                                ("alt_text", 6),
                                ("cta_link", 12),
                                ("cta_text", 13),
                            ]
                        ],
                        {"label": "Hero Block"},
                    ),
                    15: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testimonial Quote", "required": True},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Author Name", "required": True},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Author Title (Optional)", "required": False},
                    ),
                    18: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Author Image (Optional)", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 15),
                                ("author_name", 16),
                                ("author_title", 17),
                                ("author_image", 18),
                            ]
                        ],
                        {"label": "Testimonial Block"},
                    ),
                    20: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "label": "Number of Publications",
                            "max_value": 20,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("number_of_publications", 20)]],
                        {"label": "Recent Publications Block"},
                    ),
                    22: ("core.blocks.CardListBlock", (), {"label": "Card List Block"}),
                },
                help_text="The main content of the home page.",
                verbose_name="Home page content",
            ),
        ),
    ]
