# Generated by Django 6.0.2 on 2026-03-04 20:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 3),
                    ("image", 7),
                    ("vertical_spacer", 10),
                    ("call_to_action_button", 15),
                    ("two_column", 18),
                    ("hero", 25),
                    ("testimonial_list", 26),
                    ("recent_publications", 28),
                    ("cards", 29),
                    ("faq", 30),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Justification",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "Content",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    2: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "label": "Max Width (in pixels, optional)",
                            "min_value": 0,
                            "placeholder": "Leave blank for full width",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("justification", 0), ("text", 1), ("max_width", 2)]],
                        {},
                    ),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (1/3 Width)"),
                                ("medium", "Medium (1/2 Width)"),
                                ("large", "Large (2/3 Width)"),
                                ("full", "Full Width"),
                            ]
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the image's default alt text",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("size", 5), ("alt_text", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 20,
                            "label": "Height (in pixels)",
                            "min_value": 0,
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Hide on Mobile", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("height", 8), ("hide_on_mobile", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button Text", "required": True},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary"), ("secondary", "Secondary")],
                            "label": "Button Type",
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "label": "Button Alignment",
                        },
                    ),
                    14: ("wagtail.blocks.URLBlock", (), {"label": "Button Link", "required": True}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 11), ("style", 12), ("alignment", 13), ("url", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 3),
                                ("image", 7),
                                ("vertical_spacer", 10),
                                ("call_to_action_button", 15),
                            ]
                        ],
                        {"label": "Left Column Content"},
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 3),
                                ("image", 7),
                                ("vertical_spacer", 10),
                                ("call_to_action_button", 15),
                            ]
                        ],
                        {"label": "Right Column Content"},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 16), ("right_column", 17)]],
                        {},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {"label": "Title", "required": True}),
                    20: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Subtitle (Optional)", "required": False},
                    ),
                    21: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Background Image"},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Image Alt Text (For accessibility, SEO, and in case the image fails to load)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "label": "Call-to-Action Link (Leave blank if no CTA button)",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Call-to-Action Text (Leave blank if no CTA button)",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 19),
                                ("subtitle", 20),
                                ("image", 21),
                                ("alt_text", 22),
                                ("cta_link", 23),
                                ("cta_text", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("core.blocks.TestimonialListBlock", (), {}),
                    27: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "label": "Number of Publications",
                            "max_value": 20,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("number_of_publications", 27)]], {}),
                    29: ("core.blocks.CardListBlock", (), {}),
                    30: ("core.blocks.FAQBlock", (), {}),
                },
                help_text="The main content of the home page.",
                verbose_name="Home page content",
            ),
        ),
    ]
