# Generated by Django 6.0.2 on 2026-02-26 19:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 3),
                    ("text_centered", 4),
                    ("image", 5),
                    ("image_text", 10),
                    ("faq", 11),
                    ("two_column", 14),
                    ("hero", 20),
                    ("testimonial", 25),
                    ("testimonial_list", 26),
                    ("recent_publications", 28),
                    ("cards", 29),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "DEPRECATED Text",
                            "template": "core/blocks/text_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Justification",
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "Content",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("justification", 1), ("text", 2)]], {}),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "label": "DEPRECATED Centered Text",
                            "template": "core/blocks/centered_text_block.html",
                        },
                    ),
                    5: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"label": "Image", "template": "core/blocks/image_block.html"},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image Position",
                        },
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": True}),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Image Alt Text (For accessibility, SEO, and in case the image fails to load)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("position", 6), ("paragraph", 7), ("image", 8), ("alt_text", 9)]],
                        {},
                    ),
                    11: ("core.blocks.FAQBlock", (), {}),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 3), ("image", 5), ("faq", 11)]],
                        {"label": "Left Column Content"},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 3), ("image", 5), ("faq", 11)]],
                        {"label": "Right Column Content"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 12), ("right_column", 13)]],
                        {},
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {"label": "Title", "required": True}),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Subtitle (Optional)", "required": False},
                    ),
                    17: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Background Image"},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "label": "Call-to-Action Link (Leave blank if no CTA button)",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Call-to-Action Text (Leave blank if no CTA button)",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("subtitle", 16),
                                ("image", 17),
                                ("alt_text", 9),
                                ("cta_link", 18),
                                ("cta_text", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testimonial Quote", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Author Name", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Author Title (Optional)", "required": False},
                    ),
                    24: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Author Image (Optional)", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 21),
                                ("author_name", 22),
                                ("author_title", 23),
                                ("author_image", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("core.blocks.TestimonialListBlock", (), {}),
                    27: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "label": "Number of Publications",
                            "max_value": 20,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("number_of_publications", 27)]], {}),
                    29: ("core.blocks.CardListBlock", (), {}),
                },
                help_text="The main content of the home page.",
                verbose_name="Home page content",
            ),
        ),
    ]
