# Generated by Django 6.0.3 on 2026-10-07 14:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 6),
                    ("section", 27),
                    ("join", 32),
                    ("open_projects", 35),
                    ("upcoming_events", 37),
                    ("projects_map", 38),
                    ("recent_publications", 40),
                    ("rich_text", 44),
                    ("image", 45),
                    ("two_column", 52),
                    ("cards", 53),
                    ("testimonial_list", 54),
                    ("faq", 55),
                    ("vertical_spacer", 56),
                    ("call_to_action_button", 57),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Title", "required": True}),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Subtitle (Optional)", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Background Image"},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Image Alt Text (For accessibility, SEO, and in case the image fails to load)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "label": "Call-to-Action Link (Leave blank if no CTA button)",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Call-to-Action Text (Leave blank if no CTA button)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("image", 2),
                                ("alt_text", 3),
                                ("cta_link", 4),
                                ("cta_text", 5),
                            ]
                        ],
                        {"group": "Sections"},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Shown above the title, e.g. “Who we are”.",
                            "label": "Small label",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 120, "required": False},
                    ),
                    9: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Introduction", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("plain", "Plain"), ("sand", "Sand"), ("navy", "Navy")],
                            "label": "Background",
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Title above the content"),
                                ("split", "Title on the left, content on the right"),
                            ],
                            "label": "Layout",
                        },
                    ),
                    12: ("home.blocks.SectionTextBlock", (), {}),
                    13: ("home.blocks.StepsBlock", (), {}),
                    14: ("home.blocks.KeyFiguresBlock", (), {}),
                    15: ("home.blocks.QuotesBlock", (), {}),
                    16: ("home.blocks.SectionFAQBlock", (), {}),
                    17: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (1/3 Width)"),
                                ("medium", "Medium (1/2 Width)"),
                                ("large", "Large (2/3 Width)"),
                                ("full", "Full Width"),
                            ]
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the image's default alt text",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 17), ("size", 18), ("alt_text", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button Text", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary"), ("secondary", "Secondary")],
                            "label": "Button Type",
                        },
                    ),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "label": "Button Alignment",
                        },
                    ),
                    24: ("wagtail.blocks.URLBlock", (), {"label": "Button Link", "required": True}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 21), ("style", 22), ("alignment", 23), ("url", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 12),
                                ("steps", 13),
                                ("key_figures", 14),
                                ("quotes", 15),
                                ("faq", 16),
                                ("image", 20),
                                ("button", 25),
                            ]
                        ],
                        {"label": "Content", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("title", 8),
                                ("introduction", 9),
                                ("tone", 10),
                                ("layout", 11),
                                ("content", 26),
                            ]
                        ],
                        {},
                    ),
                    28: ("wagtail.blocks.CharBlock", (), {"label": "Title", "max_length": 120}),
                    29: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": False}),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leads to the registration form.",
                            "label": "Button for visitors",
                            "max_length": 40,
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leads to their email notification settings.",
                            "label": "Button for signed-in members",
                            "max_length": 40,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 28), ("text", 29), ("button", 30), ("member_button", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Small label", "max_length": 40, "required": False},
                    ),
                    34: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Maximum number of projects",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 33), ("title", 28), ("limit", 34)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Maximum number of events",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 33), ("title", 28), ("limit", 36)]],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 33), ("title", 28), ("introduction", 9)]],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "label": "Number of Publications",
                            "max_value": 20,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("number_of_publications", 39)]],
                        {"group": "Live content"},
                    ),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Justification",
                        },
                    ),
                    42: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "Content",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    43: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "label": "Max Width (in pixels, optional)",
                            "min_value": 0,
                            "placeholder": "Leave blank for full width",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("justification", 41), ("text", 42), ("max_width", 43)]],
                        {"group": "Other blocks"},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 17), ("size", 18), ("alt_text", 19)]],
                        {"group": "Other blocks"},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("justification", 41), ("text", 42), ("max_width", 43)]],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 20,
                            "label": "Height (in pixels)",
                            "min_value": 0,
                            "required": True,
                        },
                    ),
                    48: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Hide on Mobile", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("height", 47), ("hide_on_mobile", 48)]],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 46),
                                ("image", 20),
                                ("vertical_spacer", 49),
                                ("call_to_action_button", 25),
                            ]
                        ],
                        {"label": "Left Column Content"},
                    ),
                    51: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 46),
                                ("image", 20),
                                ("vertical_spacer", 49),
                                ("call_to_action_button", 25),
                            ]
                        ],
                        {"label": "Right Column Content"},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 50), ("right_column", 51)]],
                        {"group": "Other blocks"},
                    ),
                    53: ("core.blocks.CardListBlock", (), {"group": "Other blocks"}),
                    54: ("core.blocks.TestimonialListBlock", (), {"group": "Other blocks"}),
                    55: ("core.blocks.FAQBlock", (), {"group": "Other blocks"}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("height", 47), ("hide_on_mobile", 48)]],
                        {"group": "Other blocks"},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 21), ("style", 22), ("alignment", 23), ("url", 24)]],
                        {"group": "Other blocks"},
                    ),
                },
                help_text="The main content of the home page.",
                verbose_name="Home page content",
            ),
        ),
    ]
