# Generated by Django 6.0.1 on 2026-01-25 10:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description shown in lists.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("text", 0), ("image", 1), ("image_text", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "document-link",
                                        "ul",
                                        "ol",
                                        "blockquote",
                                        "superscript",
                                        "subscript",
                                    ],
                                    "label": "Text",
                                    "template": "core/blocks/rich_text_block.html",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"label": "Image", "template": "core/blocks/image_block.html"},
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("left", "Left"), ("right", "Right")],
                                    "label": "Image Position",
                                },
                            ),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Text", "required": True},
                            ),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image", "required": True},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Alt Text", "max_length": 255, "required": True},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("position", 2),
                                        ("paragraph", 3),
                                        ("image", 4),
                                        ("alt_text", 5),
                                    ]
                                ],
                                {
                                    "label": "Image & Text Row",
                                    "template": "core/blocks/image_text_block.html",
                                },
                            ),
                        },
                        help_text="The main content of the page.",
                        verbose_name="Content",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Main image for this publication",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Hero Image",
                    ),
                ),
                (
                    "real_type",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PublicationIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "page_introduction",
                    models.TextField(
                        blank=True,
                        default="Découvrez les projets et événements en cours et à venir dans votre quartier.",
                        help_text="Small introduction shown above the publications list.",
                        verbose_name="Page introduction",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Additional content for the publications page.",
                        verbose_name="Page body content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publications Index",
                "verbose_name_plural": "Publications Index",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "publicationpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="publications.publicationpage",
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(
                        help_text="Date et heure de début de l'événement", verbose_name="Event Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure de fin de l'événement (optionnel)",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Lieu de l'événement",
                        max_length=255,
                        verbose_name="Location",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Adresse complète de l'événement",
                        verbose_name="Address",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez si l'événement est en ligne",
                        verbose_name="Online Event",
                    ),
                ),
                (
                    "online_link",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers l'événement en ligne (si applicable)",
                        verbose_name="Online Link",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre maximum de participants (laisser vide si illimité)",
                        null=True,
                        verbose_name="Maximum Participants",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
            bases=("publications.publicationpage",),
        ),
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "publicationpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="publications.publicationpage",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("URBAN_PLANNING", "Urban Planning"),
                            ("ENVIRONMENT", "Environment"),
                            ("MOBILITY", "Mobility"),
                            ("HOUSING", "Housing"),
                            ("CULTURE", "Culture"),
                            ("SPORT", "Sport"),
                            ("EDUCATION", "Education"),
                            ("HEALTH", "Health"),
                            ("SOCIAL", "Social"),
                            ("ECONOMY", "Economy"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
            bases=("publications.publicationpage",),
        ),
    ]
