# Generated by Django 6.0.1 on 2026-01-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_active_vote_per_user_project',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
