# Generated by Django 6.0.1 on 2026-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0002_remove_vote_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure de fin de l'événement (optionnel)",
                null=True,
                verbose_name="End Date",
            ),
        ),
    ]
