# Generated by Django 6.0.1 on 2026-02-08 13:11

from django.db import migrations


def create_publication_index_page(apps, schema_editor):
    PublicationIndexPage = apps.get_model("publications", "PublicationIndexPage")
    HomePage = apps.get_model("home", "HomePage")

    home = HomePage.objects.first()

    if not home:
        raise RuntimeError(
            "HomePage does not exist. Please create a HomePage before running this migration."
        )

    if PublicationIndexPage.objects.exists():
        publication_index = PublicationIndexPage.objects.first()

        if not publication_index.show_in_menus:
            publication_index.show_in_menus = True
            publication_index.save(["show_in_menus"])
        return

    publication_index = PublicationIndexPage(
        title="Publications",
        slug="publications",
        show_in_menus=True,
        page_introduction="Découvrez les projets et événements en cours et à venir dans votre quartier.",
    )
    home.add_child(instance=publication_index)
    publication_index.save_revision().publish()


def reverse_create_publication_index_page(apps, schema_editor):
    PublicationIndexPage = apps.get_model("publications", "PublicationIndexPage")
    PublicationIndexPage.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_add_vote_models"),
    ]

    operations = [
        migrations.RunPython(
            code=create_publication_index_page,
            reverse_code=reverse_create_publication_index_page,
        )
    ]
