# Generated by Django 6.0.1 on 2026-02-08 13:11
from django.db import migrations, models

_SLUG = "publications"

# Historical models, like pedagogy/0002: the current PublicationIndexPage has
# columns this migration's schema does not have yet.


def create_publication_index_page(apps, schema_editor) -> None:
    ContentType = apps.get_model("contenttypes.ContentType")
    HomePage = apps.get_model("home", "HomePage")
    Page = apps.get_model("wagtailcore", "Page")
    PublicationIndexPage = apps.get_model("publications", "PublicationIndexPage")

    home = HomePage.objects.first()

    if not home:
        raise RuntimeError(
            "HomePage does not exist. Please create a HomePage before running this migration."
        )

    if PublicationIndexPage.objects.exists():
        PublicationIndexPage.objects.filter(show_in_menus=False).update(show_in_menus=True)
        return

    content_type, __ = ContentType.objects.get_or_create(
        app_label="publications", model="publicationindexpage"
    )
    last_child = (
        Page.objects.filter(path__startswith=home.path, depth=home.depth + 1)
        .order_by("path")
        .last()
    )
    if last_child:
        path = last_child.path[:-4] + f"{int(last_child.path[-4:]) + 1:04d}"
    else:
        path = home.path + "0001"

    PublicationIndexPage.objects.create(
        title="Publications",
        draft_title="Publications",
        slug=_SLUG,
        content_type=content_type,
        path=path,
        depth=home.depth + 1,
        numchild=0,
        url_path=home.url_path + _SLUG + "/",
        locale_id=home.locale_id,
        live=True,
        show_in_menus=True,
        page_introduction="Découvrez les projets et événements en cours et à venir dans votre quartier.",
    )
    home.numchild += 1
    home.save(update_fields=["numchild"])


def reverse_create_publication_index_page(apps, schema_editor):
    HomePage = apps.get_model("home", "HomePage")
    PublicationIndexPage = apps.get_model("publications", "PublicationIndexPage")

    for page in PublicationIndexPage.objects.all():
        HomePage.objects.filter(path=page.path[:-4]).update(numchild=models.F("numchild") - 1)
        page.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_add_vote_models"),
        ("home", "0005_alter_homepage_options"),
    ]

    operations = [
        migrations.RunPython(
            code=create_publication_index_page,
            reverse_code=reverse_create_publication_index_page,
        )
    ]
