# Generated by Django 6.0.2 on 2026-03-02 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0004_alter_publicationpage_content"),
        ("publications", "0004_create_publication_index_page"),
    ]

    operations = []
