# Generated by Django 6.0.2 on 2026-03-02 12:24

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0005_merge_20260302_1017"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Text displayed on the button",
                        max_length=255,
                        verbose_name="Button Text",
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="External URL for this link", verbose_name="URL"),
                ),
                (
                    "tooltip",
                    models.CharField(
                        blank=True,
                        help_text="Text shown on hover (optional)",
                        max_length=255,
                        verbose_name="Tooltip",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_links",
                        to="publications.projectpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Link",
                "verbose_name_plural": "External Links",
                "ordering": ["sort_order"],
            },
        ),
    ]
