# Generated by Django 6.0.2 on 2026-02-26 20:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0006_alter_publicationpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 4),
                    ("text_centered", 5),
                    ("image", 9),
                    ("image_text", 14),
                    ("vertical_spacer", 17),
                    ("call_to_action_button", 22),
                    ("two_column", 25),
                    ("faq", 26),
                    ("document", 28),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "DEPRECATED Text",
                            "template": "core/blocks/text_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Justification",
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ul",
                                "ol",
                                "blockquote",
                                "superscript",
                                "subscript",
                            ],
                            "label": "Content",
                            "template": "core/blocks/rich_text_block.html",
                        },
                    ),
                    3: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "label": "Max Width (in pixels, optional)",
                            "min_value": 0,
                            "placeholder": "Leave blank for full width",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("justification", 1), ("text", 2), ("max_width", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "label": "DEPRECATED Centered Text",
                            "template": "core/blocks/centered_text_block.html",
                        },
                    ),
                    6: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (1/3 Width)"),
                                ("medium", "Medium (1/2 Width)"),
                                ("large", "Large (2/3 Width)"),
                                ("full", "Full Width"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the image's default alt text",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 6), ("size", 7), ("alt_text", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image Position",
                        },
                    ),
                    11: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": True}),
                    12: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": True},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Image Alt Text (For accessibility, SEO, and in case the image fails to load)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("position", 10), ("paragraph", 11), ("image", 12), ("alt_text", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 20,
                            "label": "Height (in pixels)",
                            "min_value": 0,
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Hide on Mobile", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("height", 15), ("hide_on_mobile", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button Text", "required": True},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary"), ("secondary", "Secondary")],
                            "label": "Button Type",
                        },
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "label": "Button Alignment",
                        },
                    ),
                    21: ("wagtail.blocks.URLBlock", (), {"label": "Button Link", "required": True}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 18), ("style", 19), ("alignment", 20), ("url", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 4),
                                ("image", 9),
                                ("vertical_spacer", 17),
                                ("call_to_action_button", 22),
                            ]
                        ],
                        {"label": "Left Column Content"},
                    ),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 4),
                                ("image", 9),
                                ("vertical_spacer", 17),
                                ("call_to_action_button", 22),
                            ]
                        ],
                        {"label": "Right Column Content"},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 23), ("right_column", 24)]],
                        {},
                    ),
                    26: ("core.blocks.FAQBlock", (), {}),
                    27: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document", "required": True},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 18), ("style", 19), ("alignment", 20), ("document", 27)]],
                        {},
                    ),
                },
                help_text="The main content of the page.",
                verbose_name="Content",
            ),
        ),
    ]
