# Generated by Django 6.0.2 on 2026-03-03 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0006_add_show_toc"),
        ("publications", "0006_projectexternallink"),
    ]

    operations = []
