# Generated by Django 6.0.3 on 2026-06-23 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_participation_mode(apps, schema_editor):
    """Map the legacy boolean onto the new participation mode.

    The new column defaults to VOTING, so only the projects that had voting
    disabled need to be flipped to NONE.
    """
    ProjectPage = apps.get_model("publications", "ProjectPage")
    ProjectPage.objects.filter(enable_voting=False).update(participation_mode="NONE")


def backwards_participation_mode(apps, schema_editor):
    """Restore the legacy boolean from the participation mode."""
    ProjectPage = apps.get_model("publications", "ProjectPage")
    ProjectPage.objects.update(enable_voting=False)
    ProjectPage.objects.filter(participation_mode="VOTING").update(enable_voting=True)


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0008_alter_publicationpage_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="participation_mode",
            field=models.CharField(
                choices=[
                    ("NONE", "No participation"),
                    ("VOTING", "Voting"),
                    ("IDEAS", "Idea collection"),
                ],
                default="VOTING",
                help_text="Voting lets residents give an opinion; idea collection lets them propose ideas on a project still in its early stages. The two are mutually exclusive — switching keeps responses already collected.",
                max_length=20,
                verbose_name="Participation mode",
            ),
        ),
        migrations.RunPython(forwards_participation_mode, backwards_participation_mode),
        migrations.RemoveField(
            model_name="projectpage",
            name="enable_voting",
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="voting_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Leave empty for no end date (only applies to voting)",
                null=True,
                verbose_name="Voting End Date",
            ),
        ),
        migrations.CreateModel(
            name="IdeaResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "description",
                    models.TextField(
                        help_text="Describe your idea or alternative proposal for this project",
                        verbose_name="Idea",
                    ),
                ),
                (
                    "anonymize",
                    models.BooleanField(
                        default=False,
                        help_text="Hide your identity in administrator displays",
                        verbose_name="Anonymize",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea_responses",
                        to="publications.projectpage",
                        verbose_name="Project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Idea Response",
                "verbose_name_plural": "Idea Responses",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "project"), name="unique_user_project_idea"
                    )
                ],
            },
        ),
    ]
