# Generated by Django 6.0.3 on 2026-10-06 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0011_ensure_index_page_redirects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicationpage",
            name="real_type",
        ),
    ]
