# Generated by Django 6.0.3 on 2026-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0012_remove_publicationpage_real_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="address",
            field=models.TextField(
                blank=True, help_text="Full address of the event", verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="End date and time of the event (optional)",
                null=True,
                verbose_name="End Date",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="event_date",
            field=models.DateTimeField(
                help_text="Start date and time of the event", verbose_name="Event Date"
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="Check if the event takes place online",
                verbose_name="Online Event",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="location",
            field=models.CharField(
                blank=True, help_text="Venue of the event", max_length=255, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="max_participants",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of participants (leave empty if unlimited)",
                null=True,
                verbose_name="Maximum Participants",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="online_link",
            field=models.URLField(
                blank=True,
                help_text="Link to the online event (if applicable)",
                verbose_name="Online Link",
            ),
        ),
    ]
