# Generated by Django 6.0.3 on 2026-10-06 14:26

import publications.geo
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0013_english_event_help_texts"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="location",
            field=models.JSONField(
                blank=True,
                help_text="Where the project takes place: a point or an area.",
                null=True,
                validators=[publications.geo.validate_geometry],
                verbose_name="Location",
            ),
        ),
    ]
