# Generated by Django 6.0.3 on 2026-10-06 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0015_eventinterest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PollClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("closed_at", models.DateTimeField(auto_now_add=True, verbose_name="Closed at")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("END_DATE", "End date reached"),
                            ("MANUAL", "Closed by an editor"),
                        ],
                        max_length=20,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Closed by",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_closure",
                        to="publications.projectpage",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll closure",
                "verbose_name_plural": "Poll closures",
            },
        ),
    ]
