# Generated by Django 6.0.3 on 2026-10-06 14:53

import datetime
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0016_pollclosure"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("date", models.DateField(default=datetime.date.today, verbose_name="Date")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("body", models.TextField(max_length=3000, verbose_name="Text")),
                (
                    "notify_participants",
                    models.BooleanField(
                        default=True,
                        help_text="Sent once, when the page is published, to people who voted or shared an idea and asked for project updates. Untick for past events you are adding to the timeline.",
                        verbose_name="Email participants",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="publications.projectpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project update",
                "verbose_name_plural": "Project updates",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
