# Generated by Django 6.0.3 on 2026-10-07 09:37

from django.db import migrations, models

KEPT_CATEGORIES = ["ENVIRONMENT"]
FALLBACK_CATEGORY = "LIVING_ENVIRONMENT"


def remap_categories(apps, schema_editor):
    """Collapse the old categories into the new set.

    Environment stays as is; every other category becomes "Living environment
    / Public spaces / Mobility". Revisions are remapped too, so publishing an
    older draft or reverting cannot bring back a category that no longer exists.
    """
    ProjectPage = apps.get_model("publications", "ProjectPage")
    ProjectPage.objects.exclude(category__in=KEPT_CATEGORIES).update(category=FALLBACK_CATEGORY)

    ContentType = apps.get_model("contenttypes", "ContentType")
    Revision = apps.get_model("wagtailcore", "Revision")
    content_type = ContentType.objects.filter(app_label="publications", model="projectpage").first()
    if content_type is None:
        return

    for revision in Revision.objects.filter(content_type=content_type).iterator():
        category = revision.content.get("category")
        if category is None or category in KEPT_CATEGORIES:
            continue
        revision.content["category"] = FALLBACK_CATEGORY
        revision.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("publications", "0017_projectupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="category",
            field=models.CharField(
                choices=[
                    ("ENVIRONMENT", "Environment"),
                    ("LIVING_ENVIRONMENT", "Living environment / Public spaces / Mobility"),
                    ("URBAN_FORMS", "Urban forms / Housing"),
                ],
                default="LIVING_ENVIRONMENT",
                max_length=30,
                verbose_name="Category",
            ),
        ),
        # The old categories cannot be recovered, so reversing leaves data as is.
        migrations.RunPython(remap_categories, migrations.RunPython.noop),
    ]
