# Generated by Django 6.0.3 on 2026-10-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0019_index_page_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="address_location",
            field=models.JSONField(
                blank=True, editable=False, null=True, verbose_name="Address location"
            ),
        ),
    ]
