# Generated by Django 6.0.3 on 2026-10-08 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0020_address_geocoding"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tiles_auto_update",
                    models.BooleanField(
                        default=True,
                        help_text="Download the latest OpenStreetMap data for the maps at the interval below.",
                        verbose_name="Update the map automatically",
                    ),
                ),
                (
                    "tiles_update_interval_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Streets and places change slowly: once a month is enough. Each update downloads about 35 MB.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Update interval (days)",
                    ),
                ),
                (
                    "tiles_build",
                    models.CharField(
                        blank=True, editable=False, max_length=50, verbose_name="Map data version"
                    ),
                ),
                ("tiles_file", models.CharField(blank=True, editable=False, max_length=255)),
                (
                    "tiles_updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Last update"
                    ),
                ),
                (
                    "tiles_checked_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Last check"
                    ),
                ),
                (
                    "tiles_error",
                    models.TextField(blank=True, editable=False, verbose_name="Last error"),
                ),
            ],
            options={
                "verbose_name": "Map",
            },
        ),
    ]
