# Generated by Django 6.0.3 on 2026-10-08 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0021_map_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapsettings",
            name="tiles_update_interval_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Streets and places change slowly: once a month is enough. Each update downloads 35 to 60 MB, depending on the territory.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="Update interval (days)",
            ),
        ),
    ]
