# Generated by Django 6.0.3 on 2026-03-12 09:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutCommissionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("content", wagtail.fields.RichTextField(blank=True, verbose_name="Content")),
                (
                    "members",
                    wagtail.fields.StreamField(
                        [("user_list", 0)],
                        blank=True,
                        block_lookup={0: ("about.blocks.UserListBlock", (), {})},
                        verbose_name="Commission Members",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Commission Page",
                "verbose_name_plural": "About Commission Pages",
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AboutDevTeamPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("content", wagtail.fields.RichTextField(blank=True, verbose_name="Content")),
                (
                    "members",
                    wagtail.fields.StreamField(
                        [("members_list", 0)],
                        blank=True,
                        block_lookup={0: ("about.blocks.MembersListBlock", (), {})},
                        verbose_name="Dev Team Members",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Dev Team Page",
                "verbose_name_plural": "About Dev Team Pages",
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AboutIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Index Page",
                "verbose_name_plural": "About Index Pages",
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AboutWebsitePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("content", wagtail.fields.RichTextField(blank=True, verbose_name="Content")),
            ],
            options={
                "verbose_name": "About Website Page",
                "verbose_name_plural": "About Website Pages",
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
