# Generated by Django 6.0.3 on 2026-10-07 18:34

import json

import wagtail.fields
from django.db import migrations


MODELS = ("aboutwebsitepage", "aboutcommissionpage", "aboutdevteampage")


def blocks_for(html):
    return json.dumps([{"type": "text", "value": html}] if html else [])


def move_text_into_blocks(apps, schema_editor):
    """The rich text becomes one text block, on the page and its latest revision
    (the editor opens the revision)."""
    for model_name in MODELS:
        model = apps.get_model("about", model_name)
        for page in model.objects.all():
            page.content = blocks_for(page.legacy_content)
            page.save(update_fields=["content"])
            if page.latest_revision_id:
                revision = page.latest_revision
                revision.content["content"] = blocks_for(revision.content.get("content", ""))
                revision.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0003_create_about_pages"),
    ]

    operations = [
        migrations.RenameField("aboutcommissionpage", "content", "legacy_content"),
        migrations.RenameField("aboutdevteampage", "content", "legacy_content"),
        migrations.RenameField("aboutwebsitepage", "content", "legacy_content"),
        migrations.AddField(
            model_name="aboutcommissionpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("section", 21),
                    ("join", 26),
                    ("open_projects", 29),
                    ("upcoming_events", 31),
                    ("recent_publications", 33),
                    ("image", 34),
                    ("cards", 35),
                    ("faq", 36),
                    ("call_to_action_button", 37),
                ],
                blank=True,
                block_lookup={
                    0: ("about.blocks.AboutTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Shown above the title, e.g. “Who we are”.",
                            "label": "Small label",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 120, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Introduction", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("plain", "Plain"), ("sand", "Sand"), ("navy", "Navy")],
                            "label": "Background",
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Title above the content"),
                                ("split", "Title on the left, content on the right"),
                            ],
                            "label": "Layout",
                        },
                    ),
                    6: ("home.blocks.SectionTextBlock", (), {}),
                    7: ("home.blocks.StepsBlock", (), {}),
                    8: ("home.blocks.KeyFiguresBlock", (), {}),
                    9: ("home.blocks.QuotesBlock", (), {}),
                    10: ("home.blocks.SectionFAQBlock", (), {}),
                    11: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (1/3 Width)"),
                                ("medium", "Medium (1/2 Width)"),
                                ("large", "Large (2/3 Width)"),
                                ("full", "Full Width"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the image's default alt text",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 11), ("size", 12), ("alt_text", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button Text", "required": True},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary"), ("secondary", "Secondary")],
                            "label": "Button Type",
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "label": "Button Alignment",
                        },
                    ),
                    18: ("wagtail.blocks.URLBlock", (), {"label": "Button Link", "required": True}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("style", 16), ("alignment", 17), ("url", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 6),
                                ("steps", 7),
                                ("key_figures", 8),
                                ("quotes", 9),
                                ("faq", 10),
                                ("image", 14),
                                ("button", 19),
                            ]
                        ],
                        {"label": "Content", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 1),
                                ("title", 2),
                                ("introduction", 3),
                                ("tone", 4),
                                ("layout", 5),
                                ("content", 20),
                            ]
                        ],
                        {},
                    ),
                    22: ("wagtail.blocks.CharBlock", (), {"label": "Title", "max_length": 120}),
                    23: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": False}),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leads to the registration form.",
                            "label": "Button for visitors",
                            "max_length": 40,
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leads to their email notification settings.",
                            "label": "Button for signed-in members",
                            "max_length": 40,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 22), ("text", 23), ("button", 24), ("member_button", 25)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Small label", "max_length": 40, "required": False},
                    ),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Maximum number of projects",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 27), ("title", 22), ("limit", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Maximum number of events",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 27), ("title", 22), ("limit", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "label": "Number of Publications",
                            "max_value": 20,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("number_of_publications", 32)]],
                        {"group": "Live content"},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 11), ("size", 12), ("alt_text", 13)]],
                        {"group": "Other blocks"},
                    ),
                    35: ("core.blocks.CardListBlock", (), {"group": "Other blocks"}),
                    36: ("core.blocks.FAQBlock", (), {"group": "Other blocks"}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("style", 16), ("alignment", 17), ("url", 18)]],
                        {"group": "Other blocks"},
                    ),
                },
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="aboutdevteampage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("section", 21),
                    ("join", 26),
                    ("open_projects", 29),
                    ("upcoming_events", 31),
                    ("recent_publications", 33),
                    ("image", 34),
                    ("cards", 35),
                    ("faq", 36),
                    ("call_to_action_button", 37),
                ],
                blank=True,
                block_lookup={
                    0: ("about.blocks.AboutTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Shown above the title, e.g. “Who we are”.",
                            "label": "Small label",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 120, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Introduction", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("plain", "Plain"), ("sand", "Sand"), ("navy", "Navy")],
                            "label": "Background",
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Title above the content"),
                                ("split", "Title on the left, content on the right"),
                            ],
                            "label": "Layout",
                        },
                    ),
                    6: ("home.blocks.SectionTextBlock", (), {}),
                    7: ("home.blocks.StepsBlock", (), {}),
                    8: ("home.blocks.KeyFiguresBlock", (), {}),
                    9: ("home.blocks.QuotesBlock", (), {}),
                    10: ("home.blocks.SectionFAQBlock", (), {}),
                    11: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (1/3 Width)"),
                                ("medium", "Medium (1/2 Width)"),
                                ("large", "Large (2/3 Width)"),
                                ("full", "Full Width"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the image's default alt text",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 11), ("size", 12), ("alt_text", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button Text", "required": True},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary"), ("secondary", "Secondary")],
                            "label": "Button Type",
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "label": "Button Alignment",
                        },
                    ),
                    18: ("wagtail.blocks.URLBlock", (), {"label": "Button Link", "required": True}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("style", 16), ("alignment", 17), ("url", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 6),
                                ("steps", 7),
                                ("key_figures", 8),
                                ("quotes", 9),
                                ("faq", 10),
                                ("image", 14),
                                ("button", 19),
                            ]
                        ],
                        {"label": "Content", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 1),
                                ("title", 2),
                                ("introduction", 3),
                                ("tone", 4),
                                ("layout", 5),
                                ("content", 20),
                            ]
                        ],
                        {},
                    ),
                    22: ("wagtail.blocks.CharBlock", (), {"label": "Title", "max_length": 120}),
                    23: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": False}),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leads to the registration form.",
                            "label": "Button for visitors",
                            "max_length": 40,
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leads to their email notification settings.",
                            "label": "Button for signed-in members",
                            "max_length": 40,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 22), ("text", 23), ("button", 24), ("member_button", 25)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Small label", "max_length": 40, "required": False},
                    ),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Maximum number of projects",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 27), ("title", 22), ("limit", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Maximum number of events",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 27), ("title", 22), ("limit", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "label": "Number of Publications",
                            "max_value": 20,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("number_of_publications", 32)]],
                        {"group": "Live content"},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 11), ("size", 12), ("alt_text", 13)]],
                        {"group": "Other blocks"},
                    ),
                    35: ("core.blocks.CardListBlock", (), {"group": "Other blocks"}),
                    36: ("core.blocks.FAQBlock", (), {"group": "Other blocks"}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("style", 16), ("alignment", 17), ("url", 18)]],
                        {"group": "Other blocks"},
                    ),
                },
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="aboutwebsitepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("section", 21),
                    ("join", 26),
                    ("open_projects", 29),
                    ("upcoming_events", 31),
                    ("recent_publications", 33),
                    ("image", 34),
                    ("cards", 35),
                    ("faq", 36),
                    ("call_to_action_button", 37),
                ],
                blank=True,
                block_lookup={
                    0: ("about.blocks.AboutTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Shown above the title, e.g. “Who we are”.",
                            "label": "Small label",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 120, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Introduction", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("plain", "Plain"), ("sand", "Sand"), ("navy", "Navy")],
                            "label": "Background",
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Title above the content"),
                                ("split", "Title on the left, content on the right"),
                            ],
                            "label": "Layout",
                        },
                    ),
                    6: ("home.blocks.SectionTextBlock", (), {}),
                    7: ("home.blocks.StepsBlock", (), {}),
                    8: ("home.blocks.KeyFiguresBlock", (), {}),
                    9: ("home.blocks.QuotesBlock", (), {}),
                    10: ("home.blocks.SectionFAQBlock", (), {}),
                    11: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": True}),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (1/3 Width)"),
                                ("medium", "Medium (1/2 Width)"),
                                ("large", "Large (2/3 Width)"),
                                ("full", "Full Width"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use the image's default alt text",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 11), ("size", 12), ("alt_text", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button Text", "required": True},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary"), ("secondary", "Secondary")],
                            "label": "Button Type",
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "label": "Button Alignment",
                        },
                    ),
                    18: ("wagtail.blocks.URLBlock", (), {"label": "Button Link", "required": True}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("style", 16), ("alignment", 17), ("url", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 6),
                                ("steps", 7),
                                ("key_figures", 8),
                                ("quotes", 9),
                                ("faq", 10),
                                ("image", 14),
                                ("button", 19),
                            ]
                        ],
                        {"label": "Content", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 1),
                                ("title", 2),
                                ("introduction", 3),
                                ("tone", 4),
                                ("layout", 5),
                                ("content", 20),
                            ]
                        ],
                        {},
                    ),
                    22: ("wagtail.blocks.CharBlock", (), {"label": "Title", "max_length": 120}),
                    23: ("wagtail.blocks.TextBlock", (), {"label": "Text", "required": False}),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leads to the registration form.",
                            "label": "Button for visitors",
                            "max_length": 40,
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leads to their email notification settings.",
                            "label": "Button for signed-in members",
                            "max_length": 40,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 22), ("text", 23), ("button", 24), ("member_button", 25)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Small label", "max_length": 40, "required": False},
                    ),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Maximum number of projects",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 27), ("title", 22), ("limit", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Maximum number of events",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 27), ("title", 22), ("limit", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "label": "Number of Publications",
                            "max_value": 20,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("number_of_publications", 32)]],
                        {"group": "Live content"},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 11), ("size", 12), ("alt_text", 13)]],
                        {"group": "Other blocks"},
                    ),
                    35: ("core.blocks.CardListBlock", (), {"group": "Other blocks"}),
                    36: ("core.blocks.FAQBlock", (), {"group": "Other blocks"}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("style", 16), ("alignment", 17), ("url", 18)]],
                        {"group": "Other blocks"},
                    ),
                },
                verbose_name="Content",
            ),
        ),
        migrations.RunPython(move_text_into_blocks, migrations.RunPython.noop),
        migrations.RemoveField("aboutcommissionpage", "legacy_content"),
        migrations.RemoveField("aboutdevteampage", "legacy_content"),
        migrations.RemoveField("aboutwebsitepage", "legacy_content"),
    ]
