# Generated by Django 6.0.3 on 2026-10-08 16:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0004_content_blocks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutcommissionpage",
            options={
                "verbose_name": "About the association page",
                "verbose_name_plural": "About the association pages",
            },
        ),
        migrations.AlterField(
            model_name="aboutcommissionpage",
            name="members",
            field=wagtail.fields.StreamField(
                [("user_list", 0)],
                blank=True,
                block_lookup={0: ("about.blocks.UserListBlock", (), {})},
                verbose_name="Association members",
            ),
        ),
    ]
