"""Project locations stored as GeoJSON geometries (no PostGIS needed).

A location is either a Point (a precise spot) or a Polygon (an area, e.g. a
street or a park), in WGS84 longitude/latitude as GeoJSON mandates.
"""

from collections.abc import Iterable
from typing import TYPE_CHECKING, Any

from django.core.exceptions import ValidationError
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

if TYPE_CHECKING:
    from publications.models import ProjectPage

ALLOWED_GEOMETRY_TYPES = ("Point", "Polygon")

# Boundary drawn on the public map (Marseille 7e arrondissement, INSEE 13207,
# from geo.api.gouv.fr).
LOCAL_AREA_BOUNDARY_PATH = "publications/geo/marseille-7e.geojson"
# Used before the boundary has loaded and as the admin widget's default view.
LOCAL_AREA_CENTER = (43.2805, 5.3530)  # lat, lon
LOCAL_AREA_ZOOM = 14

# Self-hosted basemap: a PMTiles extract generated by `manage.py build_map_tiles`
# (not committed). Four times the span of the area around the boundary in each
# direction, so the maps open on the boundary and zoom out two levels further,
# to the whole city (Marseille, INSEE 13055, Riou islands included). They cannot
# be panned outside the extract: there are no tiles there.
LOCAL_AREA_TILES_PATH = "publications/geo/local-area.pmtiles"
LOCAL_AREA_TILES_BOUNDS = (5.0, 43.12, 5.67, 43.44)  # west, south, east, north
LOCAL_AREA_TILES_MAX_ZOOM = 15  # vector tiles stay sharp when zoomed past it


def _is_position(value: Any) -> bool:
    return (
        isinstance(value, list)
        and len(value) in (2, 3)
        and all(isinstance(c, int | float) and not isinstance(c, bool) for c in value)
        and -180 <= value[0] <= 180
        and -90 <= value[1] <= 90
    )


def _is_linear_ring(ring: Any) -> bool:
    return (
        isinstance(ring, list)
        and len(ring) >= 4
        and all(_is_position(p) for p in ring)
        and ring[0][:2] == ring[-1][:2]
    )


def validate_geometry(value: Any) -> None:
    """Accept a GeoJSON Point or Polygon geometry, reject anything else."""
    if value in (None, ""):
        return
    if not isinstance(value, dict) or value.get("type") not in ALLOWED_GEOMETRY_TYPES:
        raise ValidationError(_("The location must be a point or a polygon."))

    coordinates = value.get("coordinates")
    if value["type"] == "Point":
        valid = _is_position(coordinates)
    else:
        valid = _is_polygon(coordinates)
    if not valid:
        raise ValidationError(_("The location coordinates are invalid."))


def _is_polygon(coordinates: Any) -> bool:
    return (
        isinstance(coordinates, list)
        and len(coordinates) >= 1
        and all(_is_linear_ring(ring) for ring in coordinates)
    )


def validate_area(value: Any) -> None:
    """Accept a GeoJSON Polygon or MultiPolygon geometry, reject anything else."""
    if value in (None, ""):
        return
    if not isinstance(value, dict) or value.get("type") not in ("Polygon", "MultiPolygon"):
        raise ValidationError(_("The area must be a polygon."))
    coordinates = value.get("coordinates")
    if value["type"] == "Polygon":
        valid = _is_polygon(coordinates)
    else:
        valid = isinstance(coordinates, list) and all(_is_polygon(p) for p in coordinates)
    if not valid or not coordinates:
        raise ValidationError(_("The area coordinates are invalid."))


def _ring_contains(ring: list[list[float]], x: float, y: float) -> bool:
    """Ray casting: count the ring edges a ray going east from (x, y) crosses."""
    inside = False
    for (x1, y1, *_rest), (x2, y2, *_rest2) in zip(ring, ring[1:]):
        if (y1 > y) != (y2 > y) and x < x1 + (y - y1) * (x2 - x1) / (y2 - y1):
            inside = not inside
    return inside


def area_contains(area: dict[str, Any] | None, point: dict[str, Any] | None) -> bool:
    """Whether a GeoJSON Point lies in a Polygon or MultiPolygon (holes excluded).

    Planar test on longitude/latitude: exact enough at the scale of a city.
    """
    if not area or not point or point.get("type") != "Point":
        return False
    x, y = point["coordinates"][:2]
    polygons = [area["coordinates"]] if area["type"] == "Polygon" else area["coordinates"]
    return any(
        _ring_contains(outer, x, y) and not any(_ring_contains(hole, x, y) for hole in holes)
        for outer, *holes in polygons
    )


def project_feature(project: "ProjectPage") -> dict[str, Any]:
    """GeoJSON Feature describing a project for the public maps."""
    return {
        "type": "Feature",
        "geometry": project.location,
        "properties": {
            "title": project.title,
            "url": project.url,
            "category": project.get_category_display(),
            "description": project.description[:200],
            "participation": project.participation_mode,
            "isOpen": project.is_voting_open or project.is_ideas_open,
        },
    }


def feature_collection(projects: Iterable["ProjectPage"]) -> dict[str, Any]:
    return {
        "type": "FeatureCollection",
        "features": [project_feature(p) for p in projects if p.location],
    }


def map_config() -> dict[str, Any]:
    """Settings shared by the public maps and the admin widget."""
    west, south, east, north = LOCAL_AREA_TILES_BOUNDS
    return {
        "boundaryUrl": static(LOCAL_AREA_BOUNDARY_PATH),
        "center": LOCAL_AREA_CENTER,
        "zoom": LOCAL_AREA_ZOOM,
        "tilesUrl": static(LOCAL_AREA_TILES_PATH),
        "tilesMaxZoom": LOCAL_AREA_TILES_MAX_ZOOM,
        "maxBounds": [[south, west], [north, east]],
    }
