name: Post coverage comment

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  post-comment:
    name: Post coverage comment
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
      contents: write
      actions: read
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v18
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: python-coverage-comment-action
        continue-on-error: true

      - name: Check if artifact exists
        id: check_artifact
        run: |
          if [ ! -f python-coverage-comment-action.txt ]; then
            echo "::set-output name=skip::true"
          fi

      - name: Post comment
        if: steps.check_artifact.outputs.skip != 'true'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          COMMENT_ARTIFACT_NAME: python-coverage-comment-action
          COMMENT_FILENAME: python-coverage-comment-action.txt
